wget -nv -nc https://github.com/SeleniumHQ/selenium/archive/selenium-3.5.3.zip -O selenium.zip
7z x selenium.zip
cd selenium-selenium-3.5.3

set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
set JDK_HOME=C:\Program Files\Java\jdk1.8.0
set PATH=%JAVA_HOME%\bin;%JAVA_HOME%;%PATH%

go //javascript/webdriver/atoms/fragments/inject:active_element
go //javascript/webdriver/atoms/fragments/inject:active_element:android
go //javascript/webdriver/atoms/fragments/inject:active_element:chrome
go //javascript/webdriver/atoms/fragments/inject:active_element:firefox
go //javascript/webdriver/atoms/fragments/inject:active_element:ie
go //javascript/webdriver/atoms/fragments/inject:active_element:ios
go //javascript/webdriver/atoms/fragments/inject:clear
go //javascript/webdriver/atoms/fragments/inject:clear:android
go //javascript/webdriver/atoms/fragments/inject:clear:chrome
go //javascript/webdriver/atoms/fragments/inject:clear:firefox
go //javascript/webdriver/atoms/fragments/inject:clear:ie
go //javascript/webdriver/atoms/fragments/inject:clear:ios
go //javascript/webdriver/atoms/fragments/inject:clear_local_storage
go //javascript/webdriver/atoms/fragments/inject:clear_local_storage:android
go //javascript/webdriver/atoms/fragments/inject:clear_local_storage:chrome
go //javascript/webdriver/atoms/fragments/inject:clear_local_storage:firefox
go //javascript/webdriver/atoms/fragments/inject:clear_local_storage:ie
go //javascript/webdriver/atoms/fragments/inject:clear_local_storage:ios
go //javascript/webdriver/atoms/fragments/inject:clear_session_storage
go //javascript/webdriver/atoms/fragments/inject:clear_session_storage:android
go //javascript/webdriver/atoms/fragments/inject:clear_session_storage:chrome
go //javascript/webdriver/atoms/fragments/inject:clear_session_storage:firefox
go //javascript/webdriver/atoms/fragments/inject:clear_session_storage:ie
go //javascript/webdriver/atoms/fragments/inject:clear_session_storage:ios
go //javascript/webdriver/atoms/fragments/inject:click
go //javascript/webdriver/atoms/fragments/inject:click:android
go //javascript/webdriver/atoms/fragments/inject:click:chrome
go //javascript/webdriver/atoms/fragments/inject:click:firefox
go //javascript/webdriver/atoms/fragments/inject:click:ie
go //javascript/webdriver/atoms/fragments/inject:click:ios
go //javascript/webdriver/atoms/fragments/inject:default_content
go //javascript/webdriver/atoms/fragments/inject:default_content:android
go //javascript/webdriver/atoms/fragments/inject:default_content:chrome
go //javascript/webdriver/atoms/fragments/inject:default_content:firefox
go //javascript/webdriver/atoms/fragments/inject:default_content:ie
go //javascript/webdriver/atoms/fragments/inject:default_content:ios
go //javascript/webdriver/atoms/fragments/inject:execute_async_script
go //javascript/webdriver/atoms/fragments/inject:execute_async_script:android
go //javascript/webdriver/atoms/fragments/inject:execute_async_script:chrome
go //javascript/webdriver/atoms/fragments/inject:execute_async_script:firefox
go //javascript/webdriver/atoms/fragments/inject:execute_async_script:ie
go //javascript/webdriver/atoms/fragments/inject:execute_async_script:ios
go //javascript/webdriver/atoms/fragments/inject:execute_script
go //javascript/webdriver/atoms/fragments/inject:execute_script:android
go //javascript/webdriver/atoms/fragments/inject:execute_script:chrome
go //javascript/webdriver/atoms/fragments/inject:execute_script:firefox
go //javascript/webdriver/atoms/fragments/inject:execute_script:ie
go //javascript/webdriver/atoms/fragments/inject:execute_script:ios
go //javascript/webdriver/atoms/fragments/inject:execute_sql
go //javascript/webdriver/atoms/fragments/inject:execute_sql:android
go //javascript/webdriver/atoms/fragments/inject:execute_sql:chrome
go //javascript/webdriver/atoms/fragments/inject:execute_sql:firefox
go //javascript/webdriver/atoms/fragments/inject:execute_sql:ie
go //javascript/webdriver/atoms/fragments/inject:execute_sql:ios
go //javascript/webdriver/atoms/fragments/inject:find_element
go //javascript/webdriver/atoms/fragments/inject:find_element:android
go //javascript/webdriver/atoms/fragments/inject:find_element:chrome
go //javascript/webdriver/atoms/fragments/inject:find_element:firefox
go //javascript/webdriver/atoms/fragments/inject:find_element:ie
go //javascript/webdriver/atoms/fragments/inject:find_element:ios
go //javascript/webdriver/atoms/fragments/inject:find_elements
go //javascript/webdriver/atoms/fragments/inject:find_elements:android
go //javascript/webdriver/atoms/fragments/inject:find_elements:chrome
go //javascript/webdriver/atoms/fragments/inject:find_elements:firefox
go //javascript/webdriver/atoms/fragments/inject:find_elements:ie
go //javascript/webdriver/atoms/fragments/inject:find_elements:ios
go //javascript/webdriver/atoms/fragments/inject:frame_by_id_or_name
go //javascript/webdriver/atoms/fragments/inject:frame_by_id_or_name:android
go //javascript/webdriver/atoms/fragments/inject:frame_by_id_or_name:chrome
go //javascript/webdriver/atoms/fragments/inject:frame_by_id_or_name:firefox
go //javascript/webdriver/atoms/fragments/inject:frame_by_id_or_name:ie
go //javascript/webdriver/atoms/fragments/inject:frame_by_id_or_name:ios
go //javascript/webdriver/atoms/fragments/inject:frame_by_index
go //javascript/webdriver/atoms/fragments/inject:frame_by_index:android
go //javascript/webdriver/atoms/fragments/inject:frame_by_index:chrome
go //javascript/webdriver/atoms/fragments/inject:frame_by_index:firefox
go //javascript/webdriver/atoms/fragments/inject:frame_by_index:ie
go //javascript/webdriver/atoms/fragments/inject:frame_by_index:ios
go //javascript/webdriver/atoms/fragments/inject:get_appcache_status
go //javascript/webdriver/atoms/fragments/inject:get_appcache_status:android
go //javascript/webdriver/atoms/fragments/inject:get_appcache_status:chrome
go //javascript/webdriver/atoms/fragments/inject:get_appcache_status:firefox
go //javascript/webdriver/atoms/fragments/inject:get_appcache_status:ie
go //javascript/webdriver/atoms/fragments/inject:get_appcache_status:ios
go //javascript/webdriver/atoms/fragments/inject:get_attribute_value
go //javascript/webdriver/atoms/fragments/inject:get_attribute_value:android
go //javascript/webdriver/atoms/fragments/inject:get_attribute_value:chrome
go //javascript/webdriver/atoms/fragments/inject:get_attribute_value:firefox
go //javascript/webdriver/atoms/fragments/inject:get_attribute_value:ie
go //javascript/webdriver/atoms/fragments/inject:get_attribute_value:ios
go //javascript/webdriver/atoms/fragments/inject:get_frame_window
go //javascript/webdriver/atoms/fragments/inject:get_frame_window:android
go //javascript/webdriver/atoms/fragments/inject:get_frame_window:chrome
go //javascript/webdriver/atoms/fragments/inject:get_frame_window:firefox
go //javascript/webdriver/atoms/fragments/inject:get_frame_window:ie
go //javascript/webdriver/atoms/fragments/inject:get_frame_window:ios
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_item
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_item:android
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_item:chrome
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_item:firefox
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_item:ie
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_item:ios
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_keys
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_keys:android
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_keys:chrome
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_keys:firefox
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_keys:ie
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_keys:ios
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_size
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_size:android
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_size:chrome
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_size:firefox
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_size:ie
go //javascript/webdriver/atoms/fragments/inject:get_local_storage_size:ios
go //javascript/webdriver/atoms/fragments/inject:get_parent_frame
go //javascript/webdriver/atoms/fragments/inject:get_parent_frame:android
go //javascript/webdriver/atoms/fragments/inject:get_parent_frame:chrome
go //javascript/webdriver/atoms/fragments/inject:get_parent_frame:firefox
go //javascript/webdriver/atoms/fragments/inject:get_parent_frame:ie
go //javascript/webdriver/atoms/fragments/inject:get_parent_frame:ios
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_item
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_item:android
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_item:chrome
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_item:firefox
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_item:ie
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_item:ios
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_keys
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_keys:android
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_keys:chrome
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_keys:firefox
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_keys:ie
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_keys:ios
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_size
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_size:android
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_size:chrome
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_size:firefox
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_size:ie
go //javascript/webdriver/atoms/fragments/inject:get_session_storage_size:ios
go //javascript/webdriver/atoms/fragments/inject:get_size
go //javascript/webdriver/atoms/fragments/inject:get_size:android
go //javascript/webdriver/atoms/fragments/inject:get_size:chrome
go //javascript/webdriver/atoms/fragments/inject:get_size:firefox
go //javascript/webdriver/atoms/fragments/inject:get_size:ie
go //javascript/webdriver/atoms/fragments/inject:get_size:ios
go //javascript/webdriver/atoms/fragments/inject:get_text
go //javascript/webdriver/atoms/fragments/inject:get_text:android
go //javascript/webdriver/atoms/fragments/inject:get_text:chrome
go //javascript/webdriver/atoms/fragments/inject:get_text:firefox
go //javascript/webdriver/atoms/fragments/inject:get_text:ie
go //javascript/webdriver/atoms/fragments/inject:get_text:ios
go //javascript/webdriver/atoms/fragments/inject:get_top_left_coordinates
go //javascript/webdriver/atoms/fragments/inject:get_top_left_coordinates:android
go //javascript/webdriver/atoms/fragments/inject:get_top_left_coordinates:chrome
go //javascript/webdriver/atoms/fragments/inject:get_top_left_coordinates:firefox
go //javascript/webdriver/atoms/fragments/inject:get_top_left_coordinates:ie
go //javascript/webdriver/atoms/fragments/inject:get_top_left_coordinates:ios
go //javascript/webdriver/atoms/fragments/inject:get_value_of_css_property
go //javascript/webdriver/atoms/fragments/inject:get_value_of_css_property:android
go //javascript/webdriver/atoms/fragments/inject:get_value_of_css_property:chrome
go //javascript/webdriver/atoms/fragments/inject:get_value_of_css_property:firefox
go //javascript/webdriver/atoms/fragments/inject:get_value_of_css_property:ie
go //javascript/webdriver/atoms/fragments/inject:get_value_of_css_property:ios
go //javascript/webdriver/atoms/fragments/inject:is_displayed
go //javascript/webdriver/atoms/fragments/inject:is_displayed:android
go //javascript/webdriver/atoms/fragments/inject:is_displayed:chrome
go //javascript/webdriver/atoms/fragments/inject:is_displayed:firefox
go //javascript/webdriver/atoms/fragments/inject:is_displayed:ie
go //javascript/webdriver/atoms/fragments/inject:is_displayed:ios
go //javascript/webdriver/atoms/fragments/inject:is_enabled
go //javascript/webdriver/atoms/fragments/inject:is_enabled:android
go //javascript/webdriver/atoms/fragments/inject:is_enabled:chrome
go //javascript/webdriver/atoms/fragments/inject:is_enabled:firefox
go //javascript/webdriver/atoms/fragments/inject:is_enabled:ie
go //javascript/webdriver/atoms/fragments/inject:is_enabled:ios
go //javascript/webdriver/atoms/fragments/inject:is_selected
go //javascript/webdriver/atoms/fragments/inject:is_selected:android
go //javascript/webdriver/atoms/fragments/inject:is_selected:chrome
go //javascript/webdriver/atoms/fragments/inject:is_selected:firefox
go //javascript/webdriver/atoms/fragments/inject:is_selected:ie
go //javascript/webdriver/atoms/fragments/inject:is_selected:ios
go //javascript/webdriver/atoms/fragments/inject:mouse_click
go //javascript/webdriver/atoms/fragments/inject:mouse_click:android
go //javascript/webdriver/atoms/fragments/inject:mouse_click:chrome
go //javascript/webdriver/atoms/fragments/inject:mouse_click:firefox
go //javascript/webdriver/atoms/fragments/inject:mouse_click:ie
go //javascript/webdriver/atoms/fragments/inject:mouse_click:ios
go //javascript/webdriver/atoms/fragments/inject:mouse_double_click
go //javascript/webdriver/atoms/fragments/inject:mouse_double_click:android
go //javascript/webdriver/atoms/fragments/inject:mouse_double_click:chrome
go //javascript/webdriver/atoms/fragments/inject:mouse_double_click:firefox
go //javascript/webdriver/atoms/fragments/inject:mouse_double_click:ie
go //javascript/webdriver/atoms/fragments/inject:mouse_double_click:ios
go //javascript/webdriver/atoms/fragments/inject:mouse_down
go //javascript/webdriver/atoms/fragments/inject:mouse_down:android
go //javascript/webdriver/atoms/fragments/inject:mouse_down:chrome
go //javascript/webdriver/atoms/fragments/inject:mouse_down:firefox
go //javascript/webdriver/atoms/fragments/inject:mouse_down:ie
go //javascript/webdriver/atoms/fragments/inject:mouse_down:ios
go //javascript/webdriver/atoms/fragments/inject:mouse_move
go //javascript/webdriver/atoms/fragments/inject:mouse_move:android
go //javascript/webdriver/atoms/fragments/inject:mouse_move:chrome
go //javascript/webdriver/atoms/fragments/inject:mouse_move:firefox
go //javascript/webdriver/atoms/fragments/inject:mouse_move:ie
go //javascript/webdriver/atoms/fragments/inject:mouse_move:ios
go //javascript/webdriver/atoms/fragments/inject:mouse_up
go //javascript/webdriver/atoms/fragments/inject:mouse_up:android
go //javascript/webdriver/atoms/fragments/inject:mouse_up:chrome
go //javascript/webdriver/atoms/fragments/inject:mouse_up:firefox
go //javascript/webdriver/atoms/fragments/inject:mouse_up:ie
go //javascript/webdriver/atoms/fragments/inject:mouse_up:ios
go //javascript/webdriver/atoms/fragments/inject:remove_local_storage_item
go //javascript/webdriver/atoms/fragments/inject:remove_local_storage_item:android
go //javascript/webdriver/atoms/fragments/inject:remove_local_storage_item:chrome
go //javascript/webdriver/atoms/fragments/inject:remove_local_storage_item:firefox
go //javascript/webdriver/atoms/fragments/inject:remove_local_storage_item:ie
go //javascript/webdriver/atoms/fragments/inject:remove_local_storage_item:ios
go //javascript/webdriver/atoms/fragments/inject:remove_session_storage_item
go //javascript/webdriver/atoms/fragments/inject:remove_session_storage_item:android
go //javascript/webdriver/atoms/fragments/inject:remove_session_storage_item:chrome
go //javascript/webdriver/atoms/fragments/inject:remove_session_storage_item:firefox
go //javascript/webdriver/atoms/fragments/inject:remove_session_storage_item:ie
go //javascript/webdriver/atoms/fragments/inject:remove_session_storage_item:ios
go //javascript/webdriver/atoms/fragments/inject:send_keys_to_active_element
go //javascript/webdriver/atoms/fragments/inject:send_keys_to_active_element:android
go //javascript/webdriver/atoms/fragments/inject:send_keys_to_active_element:chrome
go //javascript/webdriver/atoms/fragments/inject:send_keys_to_active_element:firefox
go //javascript/webdriver/atoms/fragments/inject:send_keys_to_active_element:ie
go //javascript/webdriver/atoms/fragments/inject:send_keys_to_active_element:ios
go //javascript/webdriver/atoms/fragments/inject:set_local_storage_item
go //javascript/webdriver/atoms/fragments/inject:set_local_storage_item:android
go //javascript/webdriver/atoms/fragments/inject:set_local_storage_item:chrome
go //javascript/webdriver/atoms/fragments/inject:set_local_storage_item:firefox
go //javascript/webdriver/atoms/fragments/inject:set_local_storage_item:ie
go //javascript/webdriver/atoms/fragments/inject:set_local_storage_item:ios
go //javascript/webdriver/atoms/fragments/inject:set_session_storage_item
go //javascript/webdriver/atoms/fragments/inject:set_session_storage_item:android
go //javascript/webdriver/atoms/fragments/inject:set_session_storage_item:chrome
go //javascript/webdriver/atoms/fragments/inject:set_session_storage_item:firefox
go //javascript/webdriver/atoms/fragments/inject:set_session_storage_item:ie
go //javascript/webdriver/atoms/fragments/inject:set_session_storage_item:ios
go //javascript/webdriver/atoms/fragments/inject:submit
go //javascript/webdriver/atoms/fragments/inject:submit:android
go //javascript/webdriver/atoms/fragments/inject:submit:chrome
go //javascript/webdriver/atoms/fragments/inject:submit:firefox
go //javascript/webdriver/atoms/fragments/inject:submit:ie
go //javascript/webdriver/atoms/fragments/inject:submit:ios
go //javascript/webdriver/atoms/fragments/inject:type
go //javascript/webdriver/atoms/fragments/inject:type:android
go //javascript/webdriver/atoms/fragments/inject:type:chrome
go //javascript/webdriver/atoms/fragments/inject:type:firefox
go //javascript/webdriver/atoms/fragments/inject:type:ie
go //javascript/webdriver/atoms/fragments/inject:type:ios
go //javascript/webdriver/atoms/fragments:clear_local_storage
go //javascript/webdriver/atoms/fragments:clear_local_storage:android
go //javascript/webdriver/atoms/fragments:clear_local_storage:chrome
go //javascript/webdriver/atoms/fragments:clear_local_storage:firefox
go //javascript/webdriver/atoms/fragments:clear_local_storage:ie
go //javascript/webdriver/atoms/fragments:clear_local_storage:ios
go //javascript/webdriver/atoms/fragments:clear_session_storage
go //javascript/webdriver/atoms/fragments:clear_session_storage:android
go //javascript/webdriver/atoms/fragments:clear_session_storage:chrome
go //javascript/webdriver/atoms/fragments:clear_session_storage:firefox
go //javascript/webdriver/atoms/fragments:clear_session_storage:ie
go //javascript/webdriver/atoms/fragments:clear_session_storage:ios
go //javascript/webdriver/atoms/fragments:get_appcache_status
go //javascript/webdriver/atoms/fragments:get_appcache_status:android
go //javascript/webdriver/atoms/fragments:get_appcache_status:chrome
go //javascript/webdriver/atoms/fragments:get_appcache_status:firefox
go //javascript/webdriver/atoms/fragments:get_appcache_status:ie
go //javascript/webdriver/atoms/fragments:get_appcache_status:ios
go //javascript/webdriver/atoms/fragments:get_attribute
go //javascript/webdriver/atoms/fragments:get_attribute:android
go //javascript/webdriver/atoms/fragments:get_attribute:chrome
go //javascript/webdriver/atoms/fragments:get_attribute:firefox
go //javascript/webdriver/atoms/fragments:get_attribute:ie
go //javascript/webdriver/atoms/fragments:get_attribute:ios
go //javascript/webdriver/atoms/fragments:get_local_storage_item
go //javascript/webdriver/atoms/fragments:get_local_storage_item:android
go //javascript/webdriver/atoms/fragments:get_local_storage_item:chrome
go //javascript/webdriver/atoms/fragments:get_local_storage_item:firefox
go //javascript/webdriver/atoms/fragments:get_local_storage_item:ie
go //javascript/webdriver/atoms/fragments:get_local_storage_item:ios
go //javascript/webdriver/atoms/fragments:get_local_storage_key
go //javascript/webdriver/atoms/fragments:get_local_storage_key:android
go //javascript/webdriver/atoms/fragments:get_local_storage_key:chrome
go //javascript/webdriver/atoms/fragments:get_local_storage_key:firefox
go //javascript/webdriver/atoms/fragments:get_local_storage_key:ie
go //javascript/webdriver/atoms/fragments:get_local_storage_key:ios
go //javascript/webdriver/atoms/fragments:get_local_storage_keys
go //javascript/webdriver/atoms/fragments:get_local_storage_keys:android
go //javascript/webdriver/atoms/fragments:get_local_storage_keys:chrome
go //javascript/webdriver/atoms/fragments:get_local_storage_keys:firefox
go //javascript/webdriver/atoms/fragments:get_local_storage_keys:ie
go //javascript/webdriver/atoms/fragments:get_local_storage_keys:ios
go //javascript/webdriver/atoms/fragments:get_local_storage_size
go //javascript/webdriver/atoms/fragments:get_local_storage_size:android
go //javascript/webdriver/atoms/fragments:get_local_storage_size:chrome
go //javascript/webdriver/atoms/fragments:get_local_storage_size:firefox
go //javascript/webdriver/atoms/fragments:get_local_storage_size:ie
go //javascript/webdriver/atoms/fragments:get_local_storage_size:ios
go //javascript/webdriver/atoms/fragments:get_location_in_view
go //javascript/webdriver/atoms/fragments:get_location_in_view:android
go //javascript/webdriver/atoms/fragments:get_location_in_view:chrome
go //javascript/webdriver/atoms/fragments:get_location_in_view:firefox
go //javascript/webdriver/atoms/fragments:get_location_in_view:ie
go //javascript/webdriver/atoms/fragments:get_location_in_view:ios
go //javascript/webdriver/atoms/fragments:get_session_storage_item
go //javascript/webdriver/atoms/fragments:get_session_storage_item:android
go //javascript/webdriver/atoms/fragments:get_session_storage_item:chrome
go //javascript/webdriver/atoms/fragments:get_session_storage_item:firefox
go //javascript/webdriver/atoms/fragments:get_session_storage_item:ie
go //javascript/webdriver/atoms/fragments:get_session_storage_item:ios
go //javascript/webdriver/atoms/fragments:get_session_storage_key
go //javascript/webdriver/atoms/fragments:get_session_storage_key:android
go //javascript/webdriver/atoms/fragments:get_session_storage_key:chrome
go //javascript/webdriver/atoms/fragments:get_session_storage_key:firefox
go //javascript/webdriver/atoms/fragments:get_session_storage_key:ie
go //javascript/webdriver/atoms/fragments:get_session_storage_key:ios
go //javascript/webdriver/atoms/fragments:get_session_storage_keys
go //javascript/webdriver/atoms/fragments:get_session_storage_keys:android
go //javascript/webdriver/atoms/fragments:get_session_storage_keys:chrome
go //javascript/webdriver/atoms/fragments:get_session_storage_keys:firefox
go //javascript/webdriver/atoms/fragments:get_session_storage_keys:ie
go //javascript/webdriver/atoms/fragments:get_session_storage_keys:ios
go //javascript/webdriver/atoms/fragments:get_session_storage_size
go //javascript/webdriver/atoms/fragments:get_session_storage_size:android
go //javascript/webdriver/atoms/fragments:get_session_storage_size:chrome
go //javascript/webdriver/atoms/fragments:get_session_storage_size:firefox
go //javascript/webdriver/atoms/fragments:get_session_storage_size:ie
go //javascript/webdriver/atoms/fragments:get_session_storage_size:ios
go //javascript/webdriver/atoms/fragments:get_text
go //javascript/webdriver/atoms/fragments:get_text:android
go //javascript/webdriver/atoms/fragments:get_text:chrome
go //javascript/webdriver/atoms/fragments:get_text:firefox
go //javascript/webdriver/atoms/fragments:get_text:ie
go //javascript/webdriver/atoms/fragments:get_text:ios
go //javascript/webdriver/atoms/fragments:is_selected
go //javascript/webdriver/atoms/fragments:is_selected:android
go //javascript/webdriver/atoms/fragments:is_selected:chrome
go //javascript/webdriver/atoms/fragments:is_selected:firefox
go //javascript/webdriver/atoms/fragments:is_selected:ie
go //javascript/webdriver/atoms/fragments:is_selected:ios
go //javascript/webdriver/atoms/fragments:remove_local_storage_item
go //javascript/webdriver/atoms/fragments:remove_local_storage_item:android
go //javascript/webdriver/atoms/fragments:remove_local_storage_item:chrome
go //javascript/webdriver/atoms/fragments:remove_local_storage_item:firefox
go //javascript/webdriver/atoms/fragments:remove_local_storage_item:ie
go //javascript/webdriver/atoms/fragments:remove_local_storage_item:ios
go //javascript/webdriver/atoms/fragments:remove_session_storage_item
go //javascript/webdriver/atoms/fragments:remove_session_storage_item:android
go //javascript/webdriver/atoms/fragments:remove_session_storage_item:chrome
go //javascript/webdriver/atoms/fragments:remove_session_storage_item:firefox
go //javascript/webdriver/atoms/fragments:remove_session_storage_item:ie
go //javascript/webdriver/atoms/fragments:remove_session_storage_item:ios
go //javascript/webdriver/atoms/fragments:set_local_storage_item
go //javascript/webdriver/atoms/fragments:set_local_storage_item:android
go //javascript/webdriver/atoms/fragments:set_local_storage_item:chrome
go //javascript/webdriver/atoms/fragments:set_local_storage_item:firefox
go //javascript/webdriver/atoms/fragments:set_local_storage_item:ie
go //javascript/webdriver/atoms/fragments:set_local_storage_item:ios
go //javascript/webdriver/atoms/fragments:set_session_storage_item
go //javascript/webdriver/atoms/fragments:set_session_storage_item:android
go //javascript/webdriver/atoms/fragments:set_session_storage_item:chrome
go //javascript/webdriver/atoms/fragments:set_session_storage_item:firefox
go //javascript/webdriver/atoms/fragments:set_session_storage_item:ie
go //javascript/webdriver/atoms/fragments:set_session_storage_item:ios
